name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

# When a new job is pushed on a PR, cancel the old one.
concurrency:
  group: >
    ${{ github.event_name == 'pull_request'
        && format('pr-{0}', github.event.pull_request.number)
        || format('push-{0}', github.ref) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  end-to-end:
    name: End-to-end tests
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain, cache and bins
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          cache-base: main
          components: rustfmt, clippy

      - name: Build all Rust targets
        run: cargo build --all-targets --all-features --verbose

      - name: Install specific noir version
        uses: dzejkop/noirup@0.2.1
        with:
          commit: 2a79d90

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Compile and execute Nargo circuit
        working-directory: noir-examples/poseidon-rounds
        run: |
          nargo compile
          nargo execute

      - name: Generate Gnark inputs
        working-directory: noir-examples/poseidon-rounds
        run:  |
          cargo run --release --bin noir-r1cs prepare ./target/basic.json -o ./noir-proof-scheme.nps
          cargo run --release --bin noir-r1cs prove ./noir-proof-scheme.nps ./target/basic.gz -o ./noir-proof.np
          cargo run --release --bin noir-r1cs generate-gnark-inputs ./noir-proof-scheme.nps ./noir-proof.np

      - name: Upload proof artifacts
        uses: actions/upload-artifact@v4
        with:
          name: noir-artifacts
          path: |
            noir-examples/poseidon-rounds/noir-proof-scheme.nps
            noir-examples/poseidon-rounds/noir-proof.np

      - name: Run Gnark verifier
        working-directory: gnark-whir
        run: go run .